### ISSUE TITLE
Labels on plots

### ISSUE THREAD

**Issue by lmichel** [ErwanQuintin/STONKS#2]
Someone opening a plot has no way to identify  the observation it comes from and the source either.
![Capture d’écran de 2023-03-01 09-58-51](https://user-images.githubusercontent.com/11462648/222091799-1bcad2c7-66a4-4a20-9db6-9d39ca231269.png)

You should add a label providing the user with more information (date, obsid , source name, source position...)

A good way to proceed, in order not to deal with too much parameters, would be to transmit those parameters as a python dict ({obsid: "qqsdsqs", "obs_date": "qsdqsdfsd ....}. That way the plotter can work with the data it found an replace the missing one with e.g. ---

**Comment by ErwanQuintin** [comment]
This lightcurve is multi-instrument, multi-observations. The source names are the legend of the left plot, the position are basically their names, and the dates are the x-axis of the left plot (in this particular case, about 10 years of data). I have all the other information you mentioned stored backend in the MasterSource object, but I don't see:
1. A clean way to plot the OBSID list for all instruments involved, that wouldn't clutter this already busy plot
2. The point of adding this information ? All you need is on the plot already. If you were interested let's say in looking up at the individual Observations, it would be faster to use the source name than the OBSIDs

**Comment by ErwanQuintin** [comment]
Maybe I misunderstood, and you were talking about the new observation only ? In which case yes, we could retrieve this information from the OBSMLI file, and add it somewhere on the plot

**Comment by lmichel** [comment]
If the alert is included within the ACDS products, final users will appreciate to be able to get some basic meta-data telling the provenance of the plots. 
The concern is to make the plots self-consistent. You cannot assume that  users will have at any time the OBSMLI on the table.
For instance, imagine that I send to you some interesting alert plot by Email, you should then be able to get from which PPS sequence it comes from and then to query some database by using this information.
We are doing so for all other ACDS graphical products.
The idea is to add a frame with al least [OBSID, SRC_NUM, POSITION and DATE-OBS]. 
From that information you can e.g. retrieve the region on the XCatDB and build a spectrum

**Comment by ErwanQuintin** [comment]
![image](https://user-images.githubusercontent.com/40163149/222115882-f0467333-1c55-43d2-98eb-de07c3ab8782.png)

I added a fourth panel to the lightcurve, containing three sets of information: about the observation (ID, Date, Target name), about the source in question (SRCNUM, off-axis angles, ra, dec, error), and about the overall added value of STONKS (simbad classification, Short term and Long term variabilities)

**Comment by lmichel** [comment]
Perfect! Many thanks. Is that already pushed?

**Comment by ErwanQuintin** [comment]
Done ! Closing this issue now. We might want to go back on the aesthetics of the lightcurves later, they are quite ugly for now

**Comment by lmichel** [comment]
Right, let's first have something working
